<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
<?php
echo $this->headTitle('Laminas API Tools');

echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

echo $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')])
    ->prependStylesheet($this->basePath('/api-tools/css/main.min.css'))
    ->prependStylesheet($this->basePath('/api-tools/css/bootstrap.min.css'));

echo $this->headScript()
    ->prependFile($this->basePath('/api-tools/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/api-tools/js/jquery.min.js'));
?>
</head>
<body>
    <div class="container">
        <?= $this->content ?>
    </div>
    <?= $this->inlineScript() ?>
</body>
</html>
